version: '3.8'

services:
  quicksort-app:
    build: .
    container_name: quicksort-example
    volumes:
      - .:/app
    command: python quicksort.py
    
  quicksort-test:
    build: .
    container_name: quicksort-test
    volumes:
      - .:/app
    command: pytest -v
    profiles:
      - test
