apiVersion: v1
kind: Service
metadata:
  name: quicksort-app-service
  namespace: quicksort-example
  labels:
    app: quicksort-app
spec:
  selector:
    app: quicksort-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
